### ISSUE TITLE
Invalid ClassName or namespace on windows

### ISSUE THREAD

**Issue by michail1982** [ajayexpert/artisan-observer-maker#2]
DIRECTORY_SEPARATOR on win os is "\\" so when I run
artisan make:observer Subdir\MyModelObserver  result
```php 
namespace App\Observers;
```
otherwise 
artisan make:observer Subdir/MyModelObserver  result
```php
use App\Subdir/MyModel;

class Subdir/MyModelObserver 
{
    public function creating(Subdir/MyModel $subdir/mymodel )
}
```

**Comment by ajayexpert** [comment]
Class and namespace's issue fixed.

**Comment by michail1982** [comment]
@ajayexpert , tnx
